brainapp_user:
    resource: "@BrainappUserBundle/Resources/config/routing.yml"
    prefix:   /

brainapp_core:
    resource: "@BrainappCoreBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
