brainapp_core_default:
    resource: "@BrainappCoreBundle/Controller/DefaultController.php"
    type:     annotation 
    
brainapp_core_dashboard:
    resource: "@BrainappCoreBundle/Controller/DashboardController.php"
    type:     annotation 

brainapp_core_dashboard_user_categories:
    resource: "@BrainappCoreBundle/Controller/DashboardUserCategoriesController.php"
    type:     annotation 
    