brainapp_core_default:
    resource: "@BrainappCoreBundle/Controller/DefaultController.php"
    type:     annotation 
    
brainapp_core_dashboard:
    resource: "@BrainappCoreBundle/Controller/Dashboard/DashboardController.php"
    type:     annotation 

brainapp_core_dashboard_show_user_categories:
    resource: "@BrainappCoreBundle/Controller/Dashboard/DashboardShowUserCatController.php"
    type:     annotation 

add_user_main_category:
    path:  /home/usercategories/addcategory/main
    defaults: { _controller: BrainappCoreBundle:Dashboard/DashboardAddUserCat:addUserMainCategory }
   
add_user_sub_category:
    path:  /home/usercategories/addcategory/sub/{parentCatId}
    defaults: { _controller: BrainappCoreBundle:Dashboard/DashboardAddUserCat:addUserSubCategory }

add_group_main_category:
    path:  /home/groupcategories/addcategory/main
    defaults: { _controller: BrainappCoreBundle:Dashboard/DashboardAddGroupCat:addGroupMainCategory }