brainapp_core_default:
    resource: "@BrainappCoreBundle/Controller/DefaultController.php"
    type:     annotation 
    
brainapp_core_dashboard:
    resource: "@BrainappCoreBundle/Controller/Dashboard/DashboardController.php"
    type:     annotation


# Beginn der Routen für MainCategories und SubCategories
# Beginn der spezifischen Routen für MainCategories und SubCategories
create_user_main_category:
    path:  /home/usercategories/addcategory/main
    defaults: { _controller: BrainappCoreBundle:Dashboard/DashboardUserCat:createUserMainCategory }
   
create_user_sub_category:
    path:  /home/usercategories/addcategory/sub
    defaults: { _controller: BrainappCoreBundle:Dashboard/DashboardUserCat:createUserSubCategory }

show_user_main_categories:
    path:  /home/usercategories/
    defaults: { _controller: BrainappCoreBundle:Dashboard/DashboardUserCat:showUserMainCategories }
    
show_user_sub_categories:
    path:  /home/usercategories/subcategories/{parentCatId}
    defaults: { _controller: BrainappCoreBundle:Dashboard/DashboardUserCat:showUserSubCategories }
# Ende der spezifischen Routen für MainCategories und SubCategories

# Beginn der generischen Routen für MainCategories und SubCategories
edit_user_category:
    path:  /home/usercategories/editcategory
    defaults: { _controller: BrainappCoreBundle:Dashboard/DashboardUserCat:editUserCategory }
   
delete_user_category:
    path:  /home/usercategories/deletecategory
    defaults: { _controller: BrainappCoreBundle:Dashboard/DashboardUserCat:deleteUserMainCategory }
# Ende der generischen Routen für MainCategories und SubCategories
# Ende der Routen für MainCategories und SubCategories