brainapp_user_security:
    resource: "@BrainappUserBundle/Controller/SecurityController.php"
    type:     annotation 

brainapp_user_register:
    resource: "@BrainappUserBundle/Controller/RegistrationController.php"
    type:     annotation 

brainapp_user_resetting:
    resource: "@BrainappUserBundle/Controller/ResettingController.php"
    type:     annotation 

    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group