services:
#    brainapp_user.example:
#        class: Brainapp\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
      brainapp_form.registration:
        class: Brainapp\UserBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: brainapp_user_registration }
            
      brainapp_registration_complet:
        class: Brainapp\UserBundle\EventListener\RegistrationConfirmListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }
            
      login_listener:
        class: Brainapp\UserBundle\EventListener\LoginListener
        arguments: ['@security.context', '@router', '@event_dispatcher', '%first_login_path%']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login', method: onSecurityInteractiveLogin }

      authentication_handler:
        class:        Brainapp\UserBundle\Handler\AuthenticationHandler
        arguments:    ["@router", "@security.context", "@fos_user.user_manager", "@service_container"]