<?php

namespace Brainapp\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	protected function getAllOrderBy($sort)
	{
		$query = $this->createQueryBuilder('u')
			->orderBy($sort);
		
		return $query->getQuery()->getResult();
	}
}
