<?php

namespace Brainapp\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UsergroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsergroupRepository extends EntityRepository
{
}
